/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GameResult = IDL.Record({
  'bet' : IDL.Nat,
  'game' : IDL.Text,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChips' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyBonus' : IDL.Func([], [IDL.Bool], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRecentHistory' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'recordGameRound' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int], [], []),
  'toggleFavoriteGame' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GameResult = IDL.Record({
    'bet' : IDL.Nat,
    'game' : IDL.Text,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChips' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyBonus' : IDL.Func([], [IDL.Bool], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRecentHistory' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'recordGameRound' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int], [], []),
    'toggleFavoriteGame' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };