/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameResult {
  'bet' : bigint,
  'game' : string,
  'amount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type RechargeStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface RechargeRequest {
  'id' : bigint,
  'userId' : Principal,
  'txId' : string,
  'amount' : bigint,
  'method' : string,
  'status' : RechargeStatus,
  'createdAt' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChips' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyBonus' : ActorMethod<[], boolean>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getRecentHistory' : ActorMethod<[], Array<GameResult>>,
  'getPendingRechargeRequests' : ActorMethod<[], Array<RechargeRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFavorite' : ActorMethod<[string], boolean>,
  'recordGameRound' : ActorMethod<[string, bigint, bigint], undefined>,
  'toggleFavoriteGame' : ActorMethod<[string], undefined>,
  'submitRechargeRequest' : ActorMethod<[string, bigint, string], bigint>,
  'approveRechargeRequest' : ActorMethod<[bigint], boolean>,
  'rejectRechargeRequest' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
